{"timestamp": "2025-05-03T00:03:24.834043", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 10340, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:03:35.498762", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 10340, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:03:35.499393", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 10340, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:03:37.967112", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 10340, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:03:44.557581", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 10340, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:03:44.559812", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 10340, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:03:46.721378", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 10340, "thread": "Thread-3 (process_request_thread)"}
{"timestamp": "2025-05-03T00:03:46.723307", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 10340, "thread": "Thread-3 (process_request_thread)"}
{"timestamp": "2025-05-03T00:09:03.969252", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 14288, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:09:14.068272", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 14288, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:09:14.068762", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 14288, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:09:16.655178", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 14288, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:09:23.622072", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 14288, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:09:23.623244", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 14288, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:10:09.117057", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 11960, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:10:19.232074", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 11960, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:10:19.232917", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 11960, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:10:20.996604", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 11960, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:10:27.975469", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 11960, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:10:27.976943", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 11960, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:11:25.367783", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 12396, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:11:36.333234", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 12396, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:11:36.333745", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 12396, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:11:38.535215", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 12396, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:11:43.118743", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 12396, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:11:43.121031", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 12396, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:12:55.938240", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 22052, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:13:07.656549", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 22052, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:13:07.656987", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 22052, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:13:09.709104", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 22052, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:13:16.166018", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 22052, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:13:16.167509", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 22052, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:54:46.771772", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 9672, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:54:54.120942", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 9672, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:54:54.121465", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 9672, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:54:55.587756", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 9672, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:55:03.333526", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 9672, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:55:03.335014", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: Authenticate\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/20003\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 9672, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-05-03T00:56:04.687719", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 22064, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:56:17.848651", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 22064, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:56:17.849070", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 22064, "thread": "MainThread"}
{"timestamp": "2025-05-03T00:57:21.570986", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 22064, "thread": "MainThread"}
{"timestamp": "2025-05-03T01:01:23.516869", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: The number +923122722929 is unverified. Trial accounts may only make calls to verified numbers.\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/21219\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 22064, "thread": "Thread-8 (process_request_thread)"}
{"timestamp": "2025-05-03T01:01:51.077150", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: The number +923122722929 is unverified. Trial accounts may only make calls to verified numbers.\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/21219\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 22064, "thread": "Thread-8 (process_request_thread)"}
