{"timestamp": "2025-06-30T22:43:46.541460", "level": "INFO", "message": "Database tables initialized", "module": "__init__", "function": "create_app", "line": 47, "process": 15684, "thread": "MainThread"}
{"timestamp": "2025-06-30T22:44:24.457159", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 15684, "thread": "MainThread"}
{"timestamp": "2025-06-30T22:44:24.457657", "level": "INFO", "message": "Database connection established", "module": "db_handler", "function": "_init_db", "line": 26, "process": 15684, "thread": "MainThread"}
{"timestamp": "2025-06-30T22:44:26.770580", "level": "INFO", "message": "Application initialized successfully", "module": "__init__", "function": "create_app", "line": 54, "process": 15684, "thread": "MainThread"}
{"timestamp": "2025-06-30T22:44:30.708037", "level": "WARNING", "message": "Not found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "module": "__init__", "function": "not_found", "line": 74, "process": 15684, "thread": "Thread-2 (process_request_thread)"}
{"timestamp": "2025-06-30T22:44:47.694385", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: The number +923122722929 is unverified. Trial accounts may only make calls to verified numbers.\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/21219\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 15684, "thread": "Thread-3 (process_request_thread)"}
{"timestamp": "2025-06-30T22:44:47.695373", "level": "ERROR", "message": "Twilio API error: \n\u001b[31m\u001b[49mHTTP Error\u001b[0m \u001b[37m\u001b[49mYour request was:\u001b[0m\n\n\u001b[36m\u001b[49mPOST /Accounts/AC3b33ee1708fe8dd88ed7356b4867b515/Calls.json\u001b[0m\n\n\u001b[37m\u001b[49mTwilio returned the following information:\u001b[0m\n\n\u001b[34m\u001b[49mUnable to create record: The number +923122722929 is unverified. Trial accounts may only make calls to verified numbers.\u001b[0m\n\n\u001b[37m\u001b[49mMore information may be available here:\u001b[0m\n\n\u001b[34m\u001b[49mhttps://www.twilio.com/docs/errors/21219\u001b[0m\n\n", "module": "routes", "function": "initiate_call", "line": 436, "process": 15684, "thread": "Thread-3 (process_request_thread)"}
